"""Materialize installable deployment bundles from the single rule source.

Where ``convert.py`` produces the raw query per rule, this pipeline produces the
files an operator actually installs: Grafana/Loki ruler alert rules, a Suricata
ruleset, Splunk saved searches and Microsoft Sentinel queries, plus a manifest
that links every deployed artifact back to the rule revision that produced it.

The bundle is committed under ``deploy/`` so the repository ships something that
can be installed without re-deriving it. ``--check`` regenerates the bundle in
memory and fails when the committed copy has drifted.

Usage:
    python pipelines/deploy.py
    python pipelines/deploy.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from convert import make_backend, rule_files, sha256  # noqa: E402
from sigma.collection import SigmaCollection  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "deploy"

# Deployment targets: backend key, output format, comment prefix, target dir.
SIGMA_DEPLOY = {
    "loki": ("loki", "ruler", "#", "loki/rules"),
    "splunk": ("splunk", "savedsearches", "#", "splunk"),
    "sentinel": ("sentinel", None, "//", "sentinel"),
    "opensearch": ("opensearch", None, "#", "opensearch"),
}

# File extension per target.
EXTENSIONS = {
    "loki": "yaml",
    "splunk": "conf",
    "sentinel": "kql",
    "opensearch": "ppl",
}

# pySigma's Loki ruler output always names the group "Sigma rules". Loki keys
# rule groups by name within a namespace, so loading several files that share a
# name collides. Rename each group after its rule file.
LOKI_GROUP_RE = re.compile(r"^(- name:\s*).*$", re.MULTILINE)


def _rename_ruler_group(document: str, name: str) -> str:
    return LOKI_GROUP_RE.sub(rf"\g<1>{name}", document, count=1)


def _convert(backend, text: str, output_format: str | None) -> list[str]:
    collection = SigmaCollection.from_yaml(text)
    if output_format:
        result = backend.convert(collection, output_format=output_format)
    else:
        result = backend.convert(collection)
    return [result] if isinstance(result, str) else list(result)


def _native_bundle() -> tuple[dict[str, str], list[dict]]:
    """Concatenate the native Suricata rules into one installable file."""
    parts: list[str] = []
    manifest: list[dict] = []
    for rule_path in sorted((REPO_ROOT / "rules" / "native").rglob("*.rules")):
        text = rule_path.read_text(encoding="utf-8")
        relative = rule_path.relative_to(REPO_ROOT).as_posix()
        parts.append(f"# === {relative} ===\n{text.rstrip()}\n")
        manifest.append(
            {
                "source": relative,
                "source_sha256": sha256(text),
                "target": "suricata/ot-detection.rules",
                "backend": "suricata",
            }
        )
    header = (
        "# OT detection ruleset for Suricata.\n"
        "# Generated by pipelines/deploy.py; do not edit by hand.\n"
        "# Install: copy to the Suricata rules directory and reload.\n\n"
    )
    return {"suricata/ot-detection.rules": header + "\n".join(parts)}, manifest


def build_bundle() -> dict[str, str]:
    """Return the full deployment bundle as a mapping of path to content."""
    bundle: dict[str, str] = {}
    manifest: list[dict] = []

    sigma_rules = rule_files((REPO_ROOT / "rules" / "sigma").resolve())

    for target, (backend_name, output_format, comment, directory) in SIGMA_DEPLOY.items():
        backend = make_backend(backend_name)
        extension = EXTENSIONS[target]
        for rule_path in sigma_rules:
            text = rule_path.read_text(encoding="utf-8")
            queries = _convert(backend, text, output_format)
            if target == "loki":
                queries = [_rename_ruler_group(query, rule_path.stem) for query in queries]
            relative = rule_path.relative_to(REPO_ROOT).as_posix()
            artifact = f"{directory}/{rule_path.stem}.{extension}"
            body = f"{comment} source: {relative}\n" + "\n".join(queries).rstrip("\n") + "\n"
            bundle[artifact] = body
            manifest.append(
                {
                    "source": relative,
                    "source_sha256": sha256(text),
                    "target": artifact,
                    "backend": target,
                }
            )

    native_bundle, native_manifest = _native_bundle()
    bundle.update(native_bundle)
    manifest.extend(native_manifest)

    bundle["manifest.json"] = json.dumps(
        {"artifacts": sorted(manifest, key=lambda item: (item["target"], item["source"]))},
        indent=2,
    ) + "\n"
    return bundle


def write_bundle(bundle: dict[str, str], out_dir: Path) -> None:
    for relative, content in sorted(bundle.items()):
        path = out_dir / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


# Files under deploy/ that are not generated: the runbook and the Suricata
# evidence produced by a real run.
NON_GENERATED = {"DEPLOY.md", "report.md"}
NON_GENERATED_PREFIXES = ("evidence/",)


def _is_non_generated(relative: str) -> bool:
    return relative in NON_GENERATED or relative.startswith(NON_GENERATED_PREFIXES)


def check_bundle(bundle: dict[str, str], out_dir: Path) -> list[str]:
    problems: list[str] = []
    for relative, content in sorted(bundle.items()):
        path = out_dir / relative
        if not path.exists():
            problems.append(f"missing: {relative}")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(f"drift: {relative}")
    existing = {
        p.relative_to(out_dir).as_posix()
        for p in out_dir.rglob("*")
        if p.is_file()
    }
    for relative in sorted(existing - set(bundle)):
        if not _is_non_generated(relative):
            problems.append(f"unexpected: {relative}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    out_dir = Path(args.out)
    bundle = build_bundle()

    if args.check:
        problems = check_bundle(bundle, out_dir)
        if problems:
            print("deployment bundle is out of date:")
            for problem in problems:
                print(f"  - {problem}")
            return 1
        print(f"deployment bundle is up to date ({len(bundle)} files)")
        return 0

    write_bundle(bundle, out_dir)
    print(f"wrote {len(bundle)} files to {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
