"""Loki ruler documents for correlation rules.

pySigma's Loki backend finalises a rule for the ruler output format by wrapping
its query in ``sum(count_over_time(<query> [1m])) or vector(0) > 0``. That is the
log-rule idiom — alert when a matching line appeared in the last minute — and it
is correct for a log selector. A correlation's query is already a metric
expression ending in its own threshold, and a metric expression cannot be an
argument to ``count_over_time``, so Loki rejects the generated rule outright::

    syntax error: unexpected COUNT, expecting NUMBER or { or (

There is a second defect on the same path: the subquery is interpolated from the
referenced rule's *ruler* conversion result, which is a dict, so the selector
becomes a Python dict repr rather than a LogQL stream selector. Both are the same
mistake — a log-rule code path applied to a metric expression — and both
disappear when the correlation is finalised from the backend's **default** output
format, which produces the query correctly and selects the event stream.

This module does that: it takes the correct query and wraps it in the ruler
document shape the backend uses for log rules, so the alert name, annotations and
severity label are identical. It is a workaround for a defect in the pinned
backend, kept in this repository's pipeline rather than patched into the
dependency, with the reproduction recorded in docs/DESIGN_DECISIONS.md.
"""

from __future__ import annotations

import re

from sigma.correlations import SigmaCorrelationRule
from yaml import dump

# Mirrors the backend's own field_replace_pattern, so an alert name generated
# here is identical to one generated by pySigma.
ALERT_NAME_PATTERN = re.compile("[^a-zA-Z0-9_:]+")


def alert_name(rule: SigmaCorrelationRule) -> str:
    """Return the ruler alert name for a rule, as pySigma would name it."""
    return ALERT_NAME_PATTERN.sub("_", rule.title).strip("_")


def ruler_document(query: str, rule: SigmaCorrelationRule) -> str:
    """Wrap a correlation query in a Loki ruler document."""
    ruler: dict = {
        "alert": alert_name(rule),
        "annotations": {"description": rule.description, "summary": rule.title},
        "expr": query,
        "labels": {},
    }
    if rule.author:
        ruler["annotations"]["author"] = rule.author
    if rule.level:
        ruler["labels"]["severity"] = rule.level.name.lower()
    return dump({"groups": [{"name": "Sigma rules", "rules": [ruler]}]})
